### ISSUE TITLE
Nitro block to use the emoji

### ISSUE THREAD

**Issue by thc282** [EpicGazel/DiscordFreeEmojis#13]
**Describe the bug**
when click on the emoji, it display nitro page

**To Reproduce**
disable all the plugin & still pop out nitro page

**Expected behavior**
click on the emoji & will send as link

**Screenshots**
null

**Client:**
 - Desktop [OS]
 - version 1.7.2
 - BD Version 1.10.2

**Additional context**
there is another error on ZeresPluginLibrary
```
TypeError: Cannot read properties of undefined (reading 'participants')
    at https://discord.com/assets/web.afed570d83e54e09da87.js:12:5576698
    at l (https://discord.com/assets/web.afed570d83e54e09da87.js:12:9523341)
    at c (https://discord.com/assets/web.afed570d83e54e09da87.js:12:9523728)
    at l (https://discord.com/assets/web.afed570d83e54e09da87.js:12:5576672)
    at p (https://discord.com/assets/958ef280f246c8d801de.js:1:5901)
    at aA (https://discord.com/assets/web.afed570d83e54e09da87.js:12:990633)
    at l (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1045869)
    at ok (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1028864)
    at https://discord.com/assets/web.afed570d83e54e09da87.js:12:1028730
    at oG (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1028738)
    at oD (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1025823)
    at r5 (https://discord.com/assets/web.afed570d83e54e09da87.js:12:974497)
    at ob (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1026327)
    at https://discord.com/assets/web.afed570d83e54e09da87.js:12:1054414
    at ll (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1054444)
    at t.render (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1058139)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4512:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6146:49)
    at N.initializeAddon (betterdiscord/renderer.js:5:27014)
    at N.loadAddon (betterdiscord/renderer.js:5:6406)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
```

**Comment by EpicGazel** [comment]
ZeresPluginLibrary is unrelated. DiscordFreeEmojis won't work if it's disabled, I assume you didn't mean to say that? Maybe provide more details such as the console output related to DiscordFreeEmojis when you enable it and when you go to put in an emoji? (in BD settings, enable "DevTools" and press ctrl+shift+i and switch to console)

**Comment by thc282** [comment]
the plugin can enable correctly
i try on private message

last time i can still send the nitro emoji to the inputbox
but recently just will pop the submit nitro inside the emoji container

i dont think there have an erro with the console. 

further detail may update tmr

**Comment by thc282** [comment]
weird. the plugin work again
not sure why that happen in earlier day

btw, do u know can the css hide the nitro bar?
![image](https://github.com/user-attachments/assets/519662da-a0f7-4037-b7d5-9e289bd2d0bf)

**Comment by thc282** [comment]
update. i added the code inside the plugin to add the css part
![image](https://github.com/user-attachments/assets/d2f6eb14-45b4-4b46-ae76-82c9dd808fae)
<details>
    <summary>code added</summary>
    
``` js
    const DOM = BdApi.DOM;
    const css = 
    `button[class*='emojiItemDisabled'] { 
        filter: none !important; 
        outline: dotted 4px rgba(255, 255, 255, 0.46); 
        outline-offset: -2px; 
        cursor: pointer !important;
    }

    /* Makes the dark background transparent */ 
    .emojiLockIconContainer_bcf389 {
    background: rgba(0,0,0,0) !important;
    scale: 0.01 !important;
    }

    /* Makes the emoji lock icon itself too small to see */
    .emojiLockIcon__37643 {
        width: 0 !important;
    }

    /* Hides lock on server icons */
    .categoryItemLockIconContainer_bfabc4 {
        display: none;
    }

    /* Hides the "Unlock every emoji with Nitro - Get Nitro" pop-up */
    .upsellContainer_a3bc57 {
        display: none;
    }

    /* Hides the divider between "Frequently Used" and server emojis */
    .nitroTopDividerContainer_e8f337 {
        display: none;
    }

    /* Makes the pink background behind "locked" emojis transparent. */
    .categorySectionNitroLocked_a3bc57 {
        background-color: transparent;
    }


    /* Other misc rules */
    /* Make (normal) text emojis bigger */
    .emoji.jumboable {
        width:150px;
        height:150px;
    }

    /* Really big emoji/sticker/gif drawer */
    .positionLayer_af5dbb {
        height: calc(100vh - 220px);
    }

    /* Hide send gift button */
    button[aria-label="Send a gift"] {
        visibility: hidden;
        display: none;
    }
    `
```

</details>

## inside Start()
![image](https://github.com/user-attachments/assets/5b4b5ee6-9576-4a36-8934-90ec58cf12ea)
``` js
function Start(){
   .......
   .......
   DOM.addStyle('FreeEmojis', css)
}
```

## inside Stop()
![image](https://github.com/user-attachments/assets/a11548a9-dc9c-407a-8c01-8e5acd3fd0a1)
``` js
function Stop(){
   ....
   ....
   DOM.removeStyle('FreeEmojis')
}
