### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by dylthom** [EpicGazel/DiscordFreeEmojis#24]
This doesn't seem to work anymore. After selecting the emoji it flashes for a second before disappearing.

**Comment by DanzoGit** [comment]
Yes, there's the problem with animated smileys again. It seems that any of the parameters can break the animation. But if there are no parameters at all, it's fine.

**Comment by EpicGazel** [comment]
Use https://github.com/EpicGazel/DiscordFreeEmojis/blob/master/DiscordFreeEmojisAlt.plugin.js

**Comment by dylthom** [comment]
> Use https://github.com/EpicGazel/DiscordFreeEmojis/blob/master/DiscordFreeEmojisAlt.plugin.js

The same issue occurs with this one.

**Comment by EpicGazel** [comment]
Can you paste the message to which the emoji was converted? Click to edit it and then copy and paste that.

**Comment by dylthom** [comment]
> Can you paste the message to which the emoji was converted? Click to edit it and then copy and paste that.

:phillies:

**Comment by EpicGazel** [comment]
You may have a conflicting plugin. Your ability to use emojis has been re-enabled (as not having nitro will disable this) but the link is not being used. You'll know the plugin is working when you get something like:
[󠄀](https://cdn.discordapp.com/emojis/1175007218173739028.webp?quality=lossless)

**Comment by DanzoGit** [comment]
It seems like some temporary issues with Discord. Animated emojis are working fine for me right now. I'm using the main file from the repository.

**Comment by d3aths** [comment]
Animated emojis are not working for me right now, when i pick out one from the list it just doesn't let me send the message at all

**Comment by EpicGazel** [comment]
> Animated emojis are not working for me right now, when i pick out one from the list it just doesn't let me send the message at all. Tried with both files.

Can you paste the message to which the emoji was converted? Click to edit it and then copy and paste that. For both files please.

**Comment by andrwmai** [comment]
Hi, I'm getting this error today after a new Discord update

```
TypeError: Cannot read properties of undefined (reading 'FormSwitch')
    at eval (betterdiscord://plugins/DiscordFreeEmojisAlt.plugin.js:38:61)
    at eval (betterdiscord://plugins/DiscordFreeEmojisAlt.plugin.js:354:7)
    at N.requireAddon (betterdiscord/renderer.js:5:49580)
    at N.loadAddon (betterdiscord/renderer.js:5:11930)
    at N.loadAddon (betterdiscord/renderer.js:5:47248)
    at betterdiscord/renderer.js:5:9910
```

```md
## Discord Info
stable 363557 (2113f49) Host 0.0.334 arm64 Build Override: N/A macOS 15 (24.3.0)

## BetterDiscord
stable 1.12.0

### Themes (1 Enabled):
- Frosted Glass
- midnight (Enabled)
```

**Comment by EpicGazel** [comment]
stale
